
language: node_js

node_js:
   - 0.10

install:
   - npm install -g grunt-cli
   - npm install

before_script:
   - npm install -g casperjs
   - phantomjs --version; casperjs --version
   - grunt connect:test:keepalive & #shooting up a web server for the tests

script: npm test
