language: node_js

node_js:
   - 0.10
env:
  - PHANTOMJS_EXECUTABLE=/usr/local/phantomjs/bin/phantomjs

install:
   - npm install -g grunt-cli
   - npm install

before_script:
  - npm install -g casperjs
  - phantomjs --version; casperjs --version


script: npm test
